import 'package:muzik_app_codeforany/models/artist.dart';

class ArtistResponse {
  static final List<Artist> response = [
    Artist(
      cover: 'assets/images/album_6.jpeg',
      title: 'ArtistName',
      genres: ['rock', 'pop', 'grunge'],
      nbAlbums: 2,
      nbSongs: 44,
      nbFollowers: 12000,
      nbListeners: 44000,
    ),
    Artist(
      cover: 'assets/images/album_6.jpeg',
      title: 'ArtistName',
      genres: ['rock', 'pop', 'grunge'],
      nbAlbums: 2,
      nbSongs: 44,
      nbFollowers: 12000,
      nbListeners: 44000,
    ),
    Artist(
      cover: 'assets/images/album_6.jpeg',
      title: 'ArtistName',
      genres: ['rock', 'pop', 'grunge'],
      nbAlbums: 2,
      nbSongs: 44,
      nbFollowers: 12000,
      nbListeners: 44000,
    ),
    Artist(
      cover: 'assets/images/album_6.jpeg',
      title: 'ArtistName',
      genres: ['rock', 'pop', 'grunge'],
      nbAlbums: 2,
      nbSongs: 44,
      nbFollowers: 12000,
      nbListeners: 44000,
    ),
    Artist(
      cover: 'assets/images/album_6.jpeg',
      title: 'ArtistName',
      genres: ['rock', 'pop', 'grunge'],
      nbAlbums: 2,
      nbSongs: 44,
      nbFollowers: 12000,
      nbListeners: 44000,
    ),
    Artist(
      cover: 'assets/images/album_6.jpeg',
      title: 'ArtistName',
      genres: ['rock', 'pop', 'grunge'],
      nbAlbums: 2,
      nbSongs: 44,
      nbFollowers: 12000,
      nbListeners: 44000,
    ),
    Artist(
      cover: 'assets/images/album_6.jpeg',
      title: 'ArtistName',
      genres: ['rock', 'pop', 'grunge'],
      nbAlbums: 2,
      nbSongs: 44,
      nbFollowers: 12000,
      nbListeners: 44000,
    ),
    Artist(
      cover: 'assets/images/album_6.jpeg',
      title: 'ArtistName',
      genres: ['rock', 'pop', 'grunge'],
      nbAlbums: 2,
      nbSongs: 44,
      nbFollowers: 12000,
      nbListeners: 44000,
    ),
    Artist(
      cover: 'assets/images/album_6.jpeg',
      title: 'ArtistName',
      genres: ['rock', 'pop', 'grunge'],
      nbAlbums: 2,
      nbSongs: 44,
      nbFollowers: 12000,
      nbListeners: 44000,
    ),
    Artist(
      cover: 'assets/images/album_6.jpeg',
      title: 'ArtistName',
      genres: ['rock', 'pop', 'grunge'],
      nbAlbums: 2,
      nbSongs: 44,
      nbFollowers: 12000,
      nbListeners: 44000,
    ),
  ];
}
